global:
  scrape_interval: 10s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: cadvisor
    scrape_interval: 10s
    static_configs:
    - targets: ['cadvisor:8080']
  - job_name: caliper
    scrape_interval: 10s
    static_configs:
    # assume single local caliper worker here, exposed on port 3000.
    # host.docker.internal if on mac
    # localhost otherwise
    - targets: ['host.docker.internal:3000', 'localhost:3000']
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
