test:
  workers:
    type: local
    number: 5
  rounds:
    - label: Change car owner.
      txDuration:
        - 30
      rateControl:
        - type: fixed-backlog
          opts:
            unfinished_per_client: 5
      workload:
        module: benchmarks/samples/fabric/fabcar/changeCarOwner.js
        arguments:
          assets: 1000
    - label: Query all cars.
      txDuration:
        - 30
      rateControl:
        - type: fixed-backlog
          opts:
            unfinished_per_client: 5
      workload:
        module: benchmarks/samples/fabric/fabcar/queryAllCars.js
        arguments:
          assets: 1000
          startKey: '1'
          endKey: '50'
    - label: Query a car.
      txDuration:
        - 30
      rateControl:
        - type: fixed-backlog
          opts:
            unfinished_per_client: 5
      workload:
        module: benchmarks/samples/fabric/fabcar/queryCar.js
        arguments:
          assets: 1000
    - label: Create a car.
      txDuration:
        - 30
      rateControl:
        - type: fixed-backlog
          opts:
            unfinished_per_client: 5
      workload:
        module: benchmarks/samples/fabric/fabcar/createCar.js
monitor:
  type:
    - docker
    - process
  docker:
    name:
      - all
  process:
    - command: node
      arguments: fabricClientWorker.js
      multiOutput: avg
  interval: 1
