blockchain:
  type: fabric
  config: benchmarks/scenario/simple/fabric.json
test:
  workers:
    type: local
    number: 5
  rounds:
    - label: open
      txNumber: 5000
      rateControl:
        type: fixed-feedback-rate
        opts:
          tps: 100
          sleep_time: 1000
          transactionLoad: 10
      workload:
        module: benchmarks/scenario/simple/open.js
        arguments:
          money: 10000
