test:
  name: Precompiled Transfer
  description: This is a precompiled transfer benchmark of FISCO BCOS for caliper
  workers:
    type: local
    number: 4
  rounds:
    - label: addUser
      description: generate users for transfer test later
      txNumber:
        - 1000
      rateControl:
        - type: fixed-rate
          opts:
            tps: 1000
      workload:
        module: benchmarks/samples/fisco-bcos/generate_txs_in_advance/addUser.js
    - label: generate
      description: transfer money between users
      txNumber:
        - 10000
      rateControl:
        - type: fixed-rate
          opts:
            tps: 10000
      workload:
        module: benchmarks/samples/fisco-bcos/generate_txs_in_advance/generate.js
    - label: send
      description: transfer money between users
      txNumber:
        - 10000
      rateControl:
        - type: fixed-rate
          opts:
            tps: 10000
      workload:
        module: benchmarks/samples/fisco-bcos/generate_txs_in_advance/send.js
monitor:
  type:
    - docker
    - process
  docker:
    name:
      - node0
      - node1
      - node2
      - node3
  process:
    - command: node
      arguments: fiscoBcosClientWorker.js
      multiOutput: avg
  interval: 0.2
